### ISSUE TITLE
New build (based on ver 18)

### ISSUE THREAD

**Issue by eisengrau** [gwlim/Fast-Path-LEDE-OpenWRT#23]
Dear gwlim,

I don't want to seem to nosy (we still owe you for what you are doing, including for my special request for the RB450G), but when can we expect a new build of yours? I think the community would be more interrested on a build based on the new version of OpenWRT (18.x.x eg. non-LEDE any more).

Thank you indeed!
andlor

**Comment by gwlim** [comment]
I am hesitant to update to OpenWrt 18 because it increase size but offer very little additional feature/performance boost on other commits at the same time kernel abi changes cause it to be very unstable.
I do check on new commits and backport a lot of performance improving features that are added in the new version like TCP TSQ patch, changes in Kernel Config and Wireless Optimization.
If you do benchmarks a lot you will notice them.

**Comment by gwlim** [comment]
Ok I just realised that it is impossible to get good wireless ac speeds with openwrt 17, the ath10k is too old, maybe a trunk based optimized release will be available soon.
I have tried benchmarking and the wireless ac speed is way better in trunk

**Comment by eisengrau** [comment]
Hi gwlim,

Of course, good call indeed. We'll be waiting for your new builds!

**Comment by insound** [comment]
Hi) thanks for your work. Build based at trunk with new kernell means that's is flowoffloading feature will work now?

**Comment by gwlim** [comment]
Yes builds are in (not all router models)
Choose SFE or Flow Offload up to you
